"use client";
import { useSearchParams } from "next/navigation";
import { useState } from "react";
import { basisOf, formatContext, formatNumber, joinCells, loadDerived, topRigs } from "../../lib/engine";

export default function WallClient() {
  const query = useSearchParams();
  const [rig, setRig] = useState(query.get("rig") ?? "all");
  const [category, setCategory] = useState("all");
  const [sort, setSort] = useState("toks");
  const rows = joinCells().filter((row) => rig === "all" || row.cell.rigKey === rig).filter((row) => category === "all" || row.model.category === category).sort((a, b) => sort === "runs" ? b.cell.n - a.cell.n : sort === "context" ? (b.cell.maxContextTested ?? 0) - (a.cell.maxContextTested ?? 0) : (b.cell.tokSOutMedian ?? -1) - (a.cell.tokSOutMedian ?? -1)).slice(0, 60);
  const categories = [...new Set(loadDerived().models.map((model) => model.category))];
  return <section aria-live="polite"><div className="toolbar"><label><span className="sr-only">hardware</span><select className="select" value={rig} onChange={(event) => setRig(event.target.value)}><option value="all">all hardware</option>{topRigs().filter((item) => item.runCount).slice(0, 24).map((item) => <option key={item.key} value={item.key}>{item.label} · {item.runCount} runs</option>)}</select></label><label><span className="sr-only">category</span><select className="select" value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">all categories</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label><span className="sr-only">sort</span><select className="select" value={sort} onChange={(event) => setSort(event.target.value)}><option value="toks">sort: fastest decode</option><option value="runs">sort: most runs</option><option value="context">sort: context tested</option></select></label></div><p className="summary">{rows.length} cells shown · {rows.filter((row) => basisOf(row.cell) === "measured").length} measured · {rows.filter((row) => basisOf(row.cell) === "reported").length} reported · MIN_RUNS_MEASURED = 3</p><div className="wall-list">{rows.map(({ cell, model, rig: hardware }, index) => <article className="wall-row" key={`${cell.rigKey}-${cell.modelSlug}-${cell.bits}`}><div className="wall-head"><span className="rank">#{index + 1}</span><strong className="wall-model">{model.displayName ?? model.slug}</strong><span className="badge">{model.category}</span><span className={`badge basis-${basisOf(cell)}`}>{basisOf(cell)}</span></div><div className="wall-speed">{formatNumber(cell.tokSOutMedian)} tok/s</div><p className="wall-meta">{hardware?.label ?? cell.rigKey} · n={cell.n} · {(cell.engines ?? []).join(", ") || "engine unstated"} · ctx {formatContext(cell.maxContextTested)} · {cell.bits}-bit</p><a className="wall-action" href="/console">capture / correct -&gt;</a></article>)}</div><p className="note">Rows are community cells (medians), ranked provisionally. A signed run outranks any claim.</p></section>;
}
