import { notFound } from "next/navigation";
import { basisOf, formatContext, formatNumber, loadDerived, metricOf } from "../../../lib/engine";

export function generateStaticParams() { return loadDerived().models.map((model) => ({ slug: model.slug })); }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const model = loadDerived().models.find((item) => item.slug === slug); return { title: model?.displayName ?? "Model", description: model ? `${model.displayName} community pool results by reference rig.` : "Model results." }; }

export default async function ModelPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const data = loadDerived(); const model = data.models.find((item) => item.slug === slug); if (!model) notFound(); const cells = data.pool.filter((cell) => cell.modelSlug === model.slug); const runs = cells.reduce((total, cell) => total + cell.n, 0); const median = model.medianTokS;
  const bestMetricCell = cells.map((cell) => ({ cell, metric: metricOf(cell) })).filter(({ metric }) => metric).sort((a, b) => (b.metric!.value) - (a.metric!.value))[0];
  return <main><section className="model-hero"><p className="kicker">community pool / model answer</p><h1>{model.displayName ?? model.slug}</h1><p>{model.category} · {model.hfId}</p><p className="answer"><strong>{median != null ? `${formatNumber(median)} tok/s` : bestMetricCell ? `${formatNumber(bestMetricCell.metric!.value)} ${bestMetricCell.metric!.unit}` : "No data yet"}</strong>{median != null ? " · model median" : bestMetricCell ? ` · best measured cell (${bestMetricCell.cell.rigKey})` : ""} · {formatNumber(runs, 0)} runs in the model record.</p></section><section className="model-table-wrap"><table><thead><tr><th>Reference rig</th><th>Quantization</th><th>Median result</th><th>Basis</th><th>TTFT (ms)</th><th>Peak VRAM</th><th>Max context</th><th>Engines</th></tr></thead><tbody>{cells.map((cell) => { const rig = data.hardware.find((item) => item.key === cell.rigKey); const metric = metricOf(cell); return <tr key={`${cell.rigKey}-${cell.bits ?? cell.category ?? "x"}`}><td>{rig?.label ?? cell.rigKey}{cell.resolution ? ` · ${cell.resolution}` : ""}</td><td>{cell.bits != null ? `${cell.bits}-bit` : cell.precision ?? "—"}</td><td>{metric ? `${formatNumber(metric.value)} ${metric.unit}` : `${formatNumber(cell.tokSOutMedian)} tok/s`}</td><td><span className={`badge basis-${basisOf(cell)}`}>{basisOf(cell)}</span></td><td>{formatNumber(cell.ttftMsMedian, 0)}</td><td>{formatNumber(cell.peakVramGbMedian ?? cell.peakVramGb)} GB</td><td>{formatContext(cell.maxContextTested)}</td><td>{(cell.engines ?? []).join(", ") || cell.pipeline || "-"}</td></tr>; })}</tbody></table></section><section className="section"><h2>Context tested</h2><p className="section-copy">The table above is the tested context for each exact rig and quantization cell. Empty fields remain empty rather than being filled with an estimate.</p><div className="actions"><a className="btn primary" href="/wall">back to The wall -&gt;</a><a className="btn" href="/console">capture / correct -&gt;</a></div></section></main>;
}
